# NUMPY

In [1]:
import numpy as np

In [5]:
my_array = np.array([1,10,-5,20])
my_array

array([ 1, 10, -5, 20])

In [4]:
type(my_array)

numpy.ndarray

In [7]:
print(f"the mean is {my_array.mean()}")
print(f"the std is {my_array.std()}")

the mean is 6.5
the std is 9.447221813845593


In [8]:
print(f"the multiplication by 2 is {my_array*2}")

the multiplication by 2 is [  2  20 -10  40]


In [10]:
my_arr_4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
my_arr_4x3*4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [27]:
print(f"Transposed matrix:\n{my_arr_4x3.T}")

Transposed matrix:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [16]:
print(f"elements in matrix: {my_arr_4x3.size}")
print(f"shape of matrix: {my_arr_4x3.shape}")

elements in matrix: 12
shape of matrix: (4, 3)


In [20]:
random_integers = np.random.randint(100,200,20)
random_integers

array([111, 142, 148, 112, 156, 178, 172, 132, 143, 130, 168, 168, 199,
       106, 184, 130, 152, 146, 135, 185])

In [21]:
random_integers % 2 

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1])

In [23]:
even_numbers = random_integers[random_integers % 2 == 0]
even_numbers

array([142, 148, 112, 156, 178, 172, 132, 130, 168, 168, 106, 184, 130,
       152, 146])

In [24]:
sliced_array = even_numbers[2:8]
sliced_array

array([112, 156, 178, 172, 132, 130])

In [26]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)

print(f"the two arrays are:\n{arr1}\n{arr2}")

the two arrays are:
[4 6 7 4]
[5 5 3 1]


In [30]:
print(f"the sum of the two arrays is: {arr1+arr2}")
print(f"the diff of the two arrays is: {arr1-arr2}")
print(f"the prod of the two arrays is: {arr1*arr2}")

the sum of the two arrays is: [ 9 11 10  5]
the diff of the two arrays is: [-1  1  4  3]
the prod of the two arrays is: [20 30 21  4]


In [33]:
np.dot(arr1, arr2)

np.int64(75)

In [34]:
np.sum(arr1*arr2) # equivalent to the dot prod

np.int64(75)